# Run 5 instances of that image as a service called web, limiting each one to use, 
# at most, 10% of the CPU (across all cores), and 50MB of RAM.
# Set the Compose file to version: "3" to make it swarm mode compatible. 
version: "3"
services:
  web:
    image: slondono/labs:docker-image-lab-v0.1
    deploy:
      replicas: 7
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    # Instruct web’s containers to share port 80 via a load-balanced network called 
    # webnet. (Internally, the containers themselves will publish to web’s port 80 at an ephemeral port.)
    ports:
      - "80:80"
    networks:
      - webnet
# Define the webnet network with the default settings (which is a load-balanced overlay network).
networks:
  webnet: